export let sideBarRoutes = {
  "DASHBOARD ": "/dashboard",
  "UNVERIFIED MEMBERS": "/unverifiedmembers",
  "VERIFIED MEMBERS": "/verifiedmembers",
  "PANCHAYAT LIST": "/panchayatlist",
  "PANCHAYAT REPORT": "/panchayatreport",
  "SEAT BOOKED": "/eventbooking",
  "ALL EVENT": "/event",
  "ALL POST": "/posts",
  "MANAGEMENT TEAM": "/management",
  "PUBLIC USER LIST": "/publicuserlist",
  "RECEIPT APPLICATION LIST": "/receiptapplication",
  "COMPLAIN / SOLUTION": "/complaints",
  "TESTIMONIAL ": "/testimonials",
  "PRINT DONATION SLIP": "/donations",
  "MY MESSAGE": "/mymessage",
  // "SLIDER IMAGES",
  // "COMPANY PROFILE",
  // "ABOUT US POST LIST",
  // "OBJECTIVE LIST",
  // "LOG OUT",
};
