export let sideBarRoutes = {
  "DASHBOARD ": "/dashboard",
  "UNVERIFIED MEMBERS": "/unverifiedmembers/superadmin",
  "VERIFIED MEMBERS": "/verifiedmembers/superadmin",
  "PANCHAYAT LIST": "/panchayatlist/superadmin",
  "PANCHAYAT REPORT": "/panchayatreport",
  "SEAT BOOKED": "/eventbooking",
  "ALL EVENT": "/event",
  "ALL POST": "/posts",
  "MANAGEMENT TEAM": "/management",
  "PUBLIC USER LIST": "/publicuserlist",
  "RECEIPT APPLICATION LIST": "/receiptapplication",
  "COMPLAIN / SOLUTION": "/complaints",
  "TESTIMONIAL ": "/testimonials",
  "PRINT DONATION SLIP": "/donations",
  "MY MESSAGE": "/mymessage",
  "SLIDER IMAGES": "/slider",
  "COMPANY PROFILE": "/companyprofile",
  "ABOUT US POST LIST": "/error",
  "OBJECTIVE LIST": "/objectivelist",
  "LOG OUT": "/logout",
};
